---
- name: Add repository
  get_url:
    url: "https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_{{ ansible_distribution_major_version }}/shells:fish:release:2.repo"
    dest: /etc/yum.repos.d/
  tags: &TAGS
    - fish
- name: Install app
  yum: 
    name: fish
  tags: *TAGS
