- name: Add repository
  tags: &tags
    - always
  get_url:
    url: "https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo"
    dest: /etc/yum.repos.d/

- name: Install app
  tags: *tags
  yum:
    name: fish
