- name: Add repository
  tags: &tags
    - always
  get_url:
    url: "https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo"
    dest: /etc/yum.repos.d/
- name: Install app
  tags: *tags
  dnf:
    name: fish
