- name: Add GPG key
  tags: &tags
    - always
  apt_key:
    id: D880C8E4
    url: "https://download.opensuse.org/repositories/shells:fish:release:2/Debian_{{ ansible_lsb.major_release }}.0/Release.key"
    state: present
- name: Add latest stable repository
  tags: *tags
  apt_repository:
    repo: "deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_{{ ansible_lsb.major_release }}.0/ /"
    state: present
- name: Install app
  tags: *tags
  apt:
    name: "fish"
